name: Generate Trophy
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: JaganReddy-33
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update trophy"
